Test data migrations
WildCodeSchool/reims-0219-js-its-my-city-back pull request #4
Opened 2019-06-05 13:38 UTC by seb879

add a few test data in database

2019-06-05 13:53 UTC, erabin05 requested changes
- You miss all the ```exports.down``` function in your migrations. It supposed to do the opposite of what you do in ```exports.up``` 
- And by the way you can do all your changes in only one migration

2019-06-06 07:45 UTC, dadtmt requested changes

2019-06-06 07:45 UTC, dadtmt commented on migrations/20190605091052-Table-Keyword_With_Fk.js
>    return db.createTable('keywordwithfk', {
not a proper name for a table

2019-06-06 07:45 UTC, dadtmt commented on migrations/20190605091046-Table-Keywords.js
> +    function(result){
creating tables and filling tables should not be part of the same file . one day you will want to create the db without seeding it

2019-06-06 07:55 UTC, Spartakyste commented on migrations/20190605091052-Table-Keyword_With_Fk.js
>    return db.createTable('keywordwithfk', {
Done

2019-06-06 08:27 UTC, merged